Add Contributor Covenant 2.1 copy
openela/governance pull request #7
Opened 2023-10-05 15:34 UTC by dirkmueller

2023-10-05 16:01 UTC, NeilHanlon approved these changes
looks good to me

2023-10-09 14:50 UTC, mstg requested changes

2023-10-09 14:50 UTC, mstg commented on README.md
> +[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](code_of_conduct.md)
Shouldn't the badge say 1.4 instead of 2.1?

2023-10-09 15:06 UTC, dirkmueller commented on README.md
> +[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](code_of_conduct.md)
changed

2023-10-09 15:15 UTC, mstg approved these changes

2023-10-09 15:15 UTC, mstg commented
Thanks!

2023-10-09 15:15 UTC, merged